### ISSUE TITLE
Files for problem 4 

### ISSUE THREAD

**Issue by ZadokA** [1213-Throwback/Project_4#5]
As a team member, I created the html and jsx files to begin work on problem 4.

**Comment by ZadokA** [comment]
I had some code to the HTML file for problem 4.

**Comment by DiegoLopezInc** [comment]
As a team programmer, I want to make sure all files are in for problem 4 before the due date. I used the professors solution to complete the problem since we ran out of time to make our own solution. Many thanks to the professor, one of our teammates needed to get medical test and this part was stressing them out!

Here are the files I added:
**p4.html**
![image](https://github.com/1213-Throwback/Project_4/assets/123400127/a590f540-aa41-4b86-857e-bb0126887d68)

**p4.jsx**
![image](https://github.com/1213-Throwback/Project_4/assets/123400127/dfcd55b1-7bde-4968-8c2c-154a05574f7e)
![image](https://github.com/1213-Throwback/Project_4/assets/123400127/c5f081f6-5b40-499b-ac2b-8846768df1d6)
