### ISSUE TITLE
Problem #5 Thread

### ISSUE THREAD

**Issue by albert-bastakoti** [1213-Throwback/Project_4#7]
I believed I did problem 4. I am not the most confident in my code since something has been wrong on my end resulting in me not being able run the website. I have my version of the solution on my computer but I am not sure if it will run successfully so we can look over it in class.

**Comment by DiegoLopezInc** [comment]
As a team programmer, I want to make sure all files are in for problem 5 before the due date. I used the professors solution to complete the problem since we ran out of time to make our own solution. Many thanks to the professor, one of our teammates needed to get medical test and this part was stressing them out as well! 

Here are the files added: 
**file p5.html**
![image](https://github.com/1213-Throwback/Project_4/assets/123400127/7cc2de7d-4640-44d9-a505-4d754fae1872)

**file p5.jsx:**
![image](https://github.com/1213-Throwback/Project_4/assets/123400127/22b7ff39-05c1-4d87-931b-d954e12b6f06)
